language: node_js
node_js:
  - 12

branches:
  only:
    - "production"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/yarn
    - ~/.cache

env:
  global:
    - CC_TEST_REPORTER_ID=84c6715645314b63e411673215f9d3786946176a838eecd67e683c7c251f0371

jobs:
  include:
    before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

    script:
      - yarn format:check
      - yarn lint
      - yarn test:unit:ci

    after_script:
      - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
